repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/psf/black
  #   rev: 22.6.0
  #   hooks:
  #     - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14  # Use the ref you want to point at
    hooks:
    - id: mdformat
      additional_dependencies:
      - mdformat-black
      - mdformat-gfm
      - mdformat-tables
      - mdformat-toc
